DATA_PATH="data/Wilson_disease_dataset.csv"
DIAGNOSIS="Is_Wilson_Disease"
XGB_PARAMETERS={
    "max_depth":4,
    "subsample":0.9,
    "colsample_bytree":0.9,
    "learning_rate":0.05,
    "n_estimators":600,
    "random_state":1,
    "eval_metric":"logloss"
}